### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by mstrelan** [fiasco/govcms-updater#1]
Thanks for pointing me to this updater. Unfortunately it doesn't seem to work for me and I'm hoping there's something obvious I'm missing.

My docroot is /path/to/my/repo/docroot, the builder is /path/to/my/repo/govcms-updater.

From /path/to/my/repo I ran ./govcms-updater/updater.sh 7.x-2.0-rc4 which seemed to go well up until drush finished downloading the contrib modules. I've attached the output from that point to this gist - https://gist.github.com/mstrelan/5b018aa0f9dcb63c79897cf74e028e35

Is there anything obvious I've done wrong? Thanks in advance.

**Comment by mstrelan** [comment]
Sorry I've just re-ran the updater and it seems to be working now. It seems that this line caused the failure the first time.

[phingcall] Calling Buildfile '/path/to/my/repo/govcms-updater/build/build/phing/build.xml' with target 'rm-robotstxt'

**Comment by fiasco** [comment]
Glad to hear its working - though its not clear to me why it failed first time round.
